spring:
  application:
    name: deal
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://localhost:5432/credit_bank
    username: postgres
    password: postgres
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest

server:
  port: 8082

app:
  rest:
    deal:
      prefix: /deal
    document:
      prefix: /deal/document
    admin:
      prefix: /deal/admin
  font:
    path: fonts/times.ttf
  date:
    pattern: dd MMMM yyyy

logging:
  level:
    root: info
