spring:
  application:
    name: deal
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://${WEB_HOST:localhost}:5432/credit_bank
    username: postgres
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  kafka:
    bootstrap-servers: "localhost:9092"
    consumer:
      auto-offset-reset: earliest

server:
  port: 8082

app:
  rest:
    deal:
      prefix: /deal
    document:
      prefix: /deal/document
    admin:
      prefix: /deal/admin
    page-size: 10
    request:
      calculator:
        host: ${CALCULATOR_HOST:localhost}
        port: 8081
        offers-path: /calculator/offers
        credit-path: /calculator/calc
  font:
    path: fonts/times.ttf
  date:
    pattern: dd MMMM yyyy

logging:
  level:
    root: info
    # noinspection SpellCheckingInspection
    ru.neoflex.neostudy.deal: info

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"