### Create loan statement
POST http://localhost:8080/statement
Content-Type: application/json
Cache-Control: no-store

{
  "amount": 1000000,
  "term": 24,
  "firstName": "Иван",
  "lastName": "Иванов",
  "middleName": "Петрович",
  "email": "k.d.v1991@yandex.ru",
  "birthDate": "1995-03-18",
  "passportSeries": "3535",
  "passportNumber": "555555"
}

### Choose one of four offers
### В поле statementId установить корректное значение
POST http://localhost:8080/statement/select
Content-Type: application/json
Cache-Control: no-store

{
  "statementId": "ed67eb27-48ab-4b8a-994a-9f158d4bbebc",
  "requestedAmount": 1000000,
  "totalAmount": 1163679.5531268244456968,
  "term": 24,
  "monthlyPayment": 48486.6480469510185707,
  "rate": 0.15,
  "isInsuranceEnabled": false,
  "isSalaryClient": true
}

### Finish registration
### В URL установить корректный statementId
POST http://localhost:8080/statement/registration/ed67eb27-48ab-4b8a-994a-9f158d4bbebc
Content-Type: application/json
Cache-Control: no-store

{
  "gender": "MALE",
  "maritalStatus": "MARRIED",
  "dependentAmount": 0,
  "passportIssueDate": "2012-06-11",
  "passportIssueBranch": "ГУ МВД ПО МОСКОВСКОЙ ОБЛАСТИ",
  "employment": {
	"employmentStatus": "EMPLOYED",
	"employmentINN": "12341234234",
	"salary": 200000,
	"position": "WORKER",
	"workExperienceTotal": 96,
	"workExperienceCurrent": 3
  },
  "accountNumber": "9238459887345"
}

### Denial of a loan
### В URL установить корректный statementId
GET http://localhost:8080/statement/deny/ed67eb27-48ab-4b8a-994a-9f158d4bbebc




### Create documents request
### В URL установить корректный statementId
POST http://localhost:8080/document/ed67eb27-48ab-4b8a-994a-9f158d4bbebc

### Sign documents request
### В URL установить корректный statementId
POST http://localhost:8080/document/ed67eb27-48ab-4b8a-994a-9f158d4bbebc/sign

### Verify SES code request
### В URL установить корректный statementId
POST http://localhost:8080/document/ed67eb27-48ab-4b8a-994a-9f158d4bbebc/sign/code?code=9fb71a5c-5b26-46ac-b974-3abbe0487dfb




### Set status for certain statement
### В URL установить корректный statementId
PUT http://localhost:8080/admin/statement/db80261b-33e7-4296-9a9a-5907a130ac55/status
Content-Type: application/json
Cache-Control: no-store

"CC_APPROVED"

### Get certain statement
### В URL установить корректный statementId
GET http://localhost:8080/admin/statement/db80261b-33e7-4296-9a9a-5907a130ac55

### Get all statements
### В URL установить корректный statementId
GET http://localhost:8080/admin/statement?page=1
