### Create loan statement
POST http://localhost:8080/statement
Content-Type: application/json
Cache-Control: no-store

{
  "amount": 1000000,
  "term": 24,
  "firstName": "Семён",
  "lastName": "Сидоров",
  "middleName": "Иванович",
  "email": "999DK@mail.ru",
  "birthDate": "2000-12-18",
  "passportSeries": "1234",
  "passportNumber": "515151"
}

### Choose one of four offers
### В поле statementId установить корректное значение
POST http://localhost:8080/statement/select
Content-Type: application/json
Cache-Control: no-store

{
  "statementId": "a121443c-3397-471e-b99a-96add3728a2d",
  "requestedAmount": 1000000,
  "totalAmount": 1118588.1167166018933096,
  "term": 24,
  "monthlyPayment": 46607.8381965250788879,
  "rate": 0.11,
  "isInsuranceEnabled": false,
  "isSalaryClient": true
}

### Finish registration
### В URL установить корректный statementId
POST http://localhost:8080/statement/registration/a121443c-3397-471e-b99a-96add3728a2d
Content-Type: application/json
Cache-Control: no-store

{
  "gender": "MALE",
  "maritalStatus": "MARRIED",
  "dependentAmount": 0,
  "passportIssueDate": "2012-06-11",
  "passportIssueBranch": "ГУ МВД ПО МОСКОВСКОЙ ОБЛАСТИ",
  "employment": {
	"employmentStatus": "EMPLOYED",
	"employmentINN": "123412342345",
	"salary": 200000,
	"position": "WORKER",
	"workExperienceTotal": 96,
	"workExperienceCurrent": 3
  },
  "accountNumber": "9238459887345"
}

### Denial of a loan
### В URL установить корректный statementId
GET http://localhost:8080/statement/deny/a121443c-3397-471e-b99a-96add3728a2d




### Create documents request
### В URL установить корректный statementId
POST http://localhost:8080/document/a121443c-3397-471e-b99a-96add3728a2d

### Sign documents request
### В URL установить корректный statementId
POST http://localhost:8080/document/a121443c-3397-471e-b99a-96add3728a2d/sign

### Verify SES code request
### В URL установить корректный statementId
POST http://localhost:8080/document/a121443c-3397-471e-b99a-96add3728a2d/sign/code?code=eee7ffaa-783c-4858-9acb-d18c58cc9ad5




### Set status for certain statement
### В URL установить корректный statementId
PUT http://localhost:8080/admin/statement/836002d9-bd30-47d2-81bd-c52154b2e7ef/status
Content-Type: application/json
Cache-Control: no-store

"CC_APPROVED"

### Get certain statement
### В URL установить корректный statementId
GET http://localhost:8080/admin/statement/a121443c-3397-471e-b99a-96add3728a2d

### Get all statements
### В URL установить корректный statementId
GET http://localhost:8080/admin/statement?page=1
