version: "3.9"

networks:
  kafka-net:
    name: kafka-net
    driver: bridge
  monitoring:

services:
  zookeeper:
    image: zookeeper:3.9.2@sha256:b34b773e67cf5139de0688f3e0caf2d0316db763d5dde8b8ee6af0bbd91c720c
    container_name: zookeeper
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "2181:2181"

  kafka:
    image: obsidiandynamics/kafka   # TODO заменить
    container_name: kafka
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9092:9092"
    environment:
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: DOCKER_INTERNAL:PLAINTEXT,DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_LISTENERS: DOCKER_INTERNAL://:29092,DOCKER_EXTERNAL://:9092
      KAFKA_ADVERTISED_LISTENERS: DOCKER_INTERNAL://kafka:29092,DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    restart: "no"
    networks:
      - kafka-net
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka:29092"
    depends_on:
      - "kafka"

  postgres_db:
    image: postgres:16@sha256:d0f363f8366fbc3f52d172c6e76bc27151c3d643b870e1062b4e8bfe65baf609
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
#    volumes:
#      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: credit_bank
      POSTGRES_PASSWORD: postgres

  grafana:
    container_name: grafana
    build: ./scripts/config/grafana
    ports:
      - '3000:3000'
    volumes:
      - ./scripts/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      monitoring:
        aliases:
          - grafana
  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./scripts/config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./scripts/prometheus:/prometheus
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      monitoring:
        aliases:
          - prometheus

  calculator:
    container_name: calculator
    build:
      context: ./
      dockerfile: ./calculator/Dockerfile
    restart: unless-stopped
    ports:
      - "8081:8081"

  deal:
    container_name: deal
    build:
      context: ./
      dockerfile: ./deal/Dockerfile
    restart: unless-stopped
    depends_on:
      - postgres_db
      - kafdrop
      - calculator
    ports:
      - "8082:8082"
    environment:
      WEB_HOST: postgres

  dossier:
    container_name: dossier
    build:
      context: ./
      dockerfile: ./dossier/Dockerfile
    restart: unless-stopped
    depends_on:
      - kafdrop
    ports:
      - "8084:8084"

  gateway:
    container_name: gateway
    build:
      context: ./
      dockerfile: ./gateway/Dockerfile
    restart: unless-stopped
    ports:
      - "8085:8085"

  statement:
    container_name: statement
    build:
      context: ./
      dockerfile: ./statement/Dockerfile
    restart: unless-stopped
    ports:
      - "8083:8083"