spring:
  application:
    name: statement
  profiles:
    active: default

server:
  port: 8083

app:
  rest:
    prefix: /statement
    request:
      deal:
        host: ${DEAL_HOST:localhost}
        port: 8082
        offers-path: /deal/statement
        apply-offer-path: /deal/offer/select

logging:
  level:
    root: info
    # noinspection SpellCheckingInspection
    ru.neoflex.neostudy.statement: info

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"