### Предоставление возможных предложений займа
POST http://localhost:8082/deal/statement
Content-Type: application/json
Cache-Control: no-store

{
  "amount": 1000000,
  "term": 6,
  "firstName": "Дмитрий",
  "lastName": "Кавтасьев",
  "middleName": "Владимирович",
  "email": "999DK@mail.ru",
  "birthDate": "1991-12-20",
  "passportSeries": "1234",
  "passportNumber": "123456"
}

### Применение выбранного пользователем кредитного предложения.
### В поле statementId установить корректное значение
POST http://localhost:8082/deal/offer/select
Content-Type: application/json
Cache-Control: no-store

{
  "statementId": "d28ec271-b695-48b2-870f-9bffde93335e",
  "requestedAmount": 1000000,
  "totalAmount": 1047181.7031009111294312,
  "term": 6,
  "monthlyPayment": 174530.2838501518549052,
  "rate": 0.16,
  "isInsuranceEnabled": false,
  "isSalaryClient": false
}

### Оформление условий кредита
### В URL установить корректный statementId
POST http://localhost:8082/deal/calculate/2c21d557-2315-4ddb-92eb-801827d43079
Content-Type: application/json
Cache-Control: no-store

{
  "gender": "MALE",
  "maritalStatus": "SINGLE",
  "dependentAmount": 0,
  "passportIssueDate": "2019-06-11",
  "passportIssueBranch": "ГУ МВД ПО Г. МОСКВА",
  "employment": {
	"employmentStatus": "EMPLOYED",
	"employmentINN": "12341",
	"salary": 150000,
	"position": "WORKER",
	"workExperienceTotal": 60,
	"workExperienceCurrent": 24
  },
  "accountNumber": "1231512341"
}

### Отказ клиента от кредита
### В URL установить корректный statementId
GET http://localhost:8082/deal/offer/deny/67a37ef8-298e-4d33-9cb4-f1dd1455ea72

### Запрос на формирование документов и отправку их пользователю
### В URL установить корректный statementId
POST http://localhost:8082/deal/document/93491892-331d-429f-8b83-5d867ba32cdd/send

### Запрос на подписание документов
### В URL установить корректный statementId
POST http://localhost:8082/deal/document/93491892-331d-429f-8b83-5d867ba32cdd/sign

### Подписание документов
### В URL установить корректный statementId, добавить значение параметра запроса "code", равное подписи. Её можно взять
### из ссылки, присылаемой в письме, либо сделать запрос непосредственно из письма.
POST http://localhost:8082/deal/document/67a37ef8-298e-4d33-9cb4-f1dd1455ea72/code?code=

### Установка статуса для заявки Statement
PUT http://localhost:8082/deal/admin/statement/67a37ef8-298e-4d33-9cb4-f1dd1455ea72/status
Content-Type: application/json
Cache-Control: no-store

"CC_APPROVED"

### Получить выбранную заявку
### В URL установить корректный statementId
GET http://localhost:8082/deal/admin/statement/18afdf19-d6ef-4548-a869-eac7e8429e3d

### Получить все заявки
### В URL установить корректный statementId
GET http://localhost:8082/deal/admin/statement?page=3