spring:
  application:
    name: gateway
  profiles:
    active: default

server:
  port: 8080

app:
  rest:
    prefix:
      statement: /statement
      document: /document
      admin: /admin
    request:
      statement:
        host: ${STATEMENT_HOST:localhost}
        port: 8083
        create-loan-statement-path:    /statement
        apply-offer-path:              /statement/offer
      deal:
        host:                           ${DEAL_HOST:localhost}
        port:                           8082
        calculate-credit-path:          /deal/calculate/{statementId}
        deny-offer-path:                /deal/offer/deny/{statementId}
        create-documents-path:          /deal/document/{statementId}/send
        sign-document-path:             /deal/document/{statementId}/sign
        verify-signature-path:          /deal/document/{statementId}/code
        update-statement-status-path:   /deal/admin/statement/{statementId}/status
        get-statement-path:             /deal/admin/statement/{statementId}
        get-all-statements-path:        /deal/admin/statement

logging:
  level:
    root: info
    # noinspection SpellCheckingInspection
    ru.neoflex.neostudy.gateway: info

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"