spring:
  application:
    name: calculator
  profiles:
    active: default

server:
  port: 8081

app:
  rest:
    prefix: /calculator

logging:
  level:
    root: warn
    # noinspection SpellCheckingInspection
    ru.neoflex.neostudy.calculator: debug

credit:
  insurance-percent: 1.05
  # noinspection SpellCheckingInspection
  min-amount: 30000
  min-term: 6

rate:
  base-rate: 0.16
  insurance-enabled: -0.03
  salary-client: -0.01
  employment-status:
    self-employed: 0.01
    business-owner: 0.02
  position:
    middle-manager: -0.02
    top-manager: -0.03
  marital-status:
    married: -0.03
    divorced: 0.01
  woman:
    age-from: 32
    age-to: 60
    rate: -0.03
  man:
    age-from: 30
    age-to: 55
    rate: -0.03
  non-binary:
    rate: 0.07

refusal:
  ratio-of-amount-to-salary: 25
  min-age: 20
  max-age: 65
  work-experience:
    min-total: 18
    min-current: 3