spring:
  main:
    web-application-type: reactive
  application:
    name: gatewaycloud
  profiles:
    active: default
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          /**:
            allowed-origins:
              - http://localhost:8080
              - http://localhost:8082
              - http://localhost:8083

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: Gateway
      - url: /deal/v3/api-docs
        name: MS Deal
      - url: /statement/v3/api-docs
        name: MS Statement

server:
  port: 8080

route:
  gateway:
    create-loan-statement-path: /statement
    apply-offer-path: /statement/select
    finish-registration-path: /statement/registration/{statementId}
    deny-offer-path: /statement/deny/{statementId}
    create-documents-path: /document/{statementId}
    sign-documents-path: /document/{statementId}/sign
    verify-ses-code-path: /document/{statementId}/sign/code
    update-statement-status-path: /admin/statement/{statementId}/status
    get-statement-path: /admin/statement/{statementId}
    get-all-statements-path: /admin/statement
  deal:
    host: ${DEAL_HOST:localhost}
    port: 8082
    calculate-credit-path: /deal/calculate/{statementId}
    deny-offer-path: /deal/offer/deny/{statementId}
    create-documents-path: /deal/document/{statementId}/send
    sign-document-path: /deal/document/{statementId}/sign
    verify-signature-path: /deal/document/{statementId}/code
    update-statement-status-path: /deal/admin/statement/{statementId}/status
    get-statement-path: /deal/admin/statement/{statementId}
    get-all-statements-path: /deal/admin/statement
  statement:
    host: ${STATEMENT_HOST:localhost}
    port: 8083
    apply-offer-path: /statement/offer

logging:
  level:
    root: info
    # noinspection SpellCheckingInspection
    ru.neoflex.neostudy.gateway: info

management:
  metrics:
    tags:
      application: ${spring.application.name}
  endpoint:
    metrics:
      enabled: true
    prometheus:
      enabled: true
    health:
      show-details: always
    loggers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"