spring:
  application:
    name: dossier
  profiles:
    active: default
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: "creditBankDossier"
      bootstrap-servers: "localhost:9092"
  mail:
    host: smtp.mail.ru
    port: 587
    username: creditbank.noreply@internet.ru
    password: HgHeXKY46GZ5AAbqBcpk
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    test-connection: true

app:
  bank:
    url: http://localhost:8085
    official-name: CreditBank

server:
  port: 8084

logging:
  level:
    root: info
